/**
 * ManageSpace Onboarding API
 * ManageSpace Onboarding API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GenericAddressRequestDto } from './genericAddressRequestDto';
import { SiteAmenityRequest } from './siteAmenityRequest';
import { SiteUserRequest } from './siteUserRequest';

export class CreateDefaultDataRequest {
    /**
    * Organization name
    */
    'orgName': string;
    /**
    * Organization name
    */
    'siteName': string;
    /**
    * Fields to skip during default data creation.
    */
    'skip'?: Array<string>;
    'orgAddress'?: GenericAddressRequestDto;
    'siteAddress'?: GenericAddressRequestDto;
    /**
    * Org Phone number
    */
    'sitePhoneNumber'?: string;
    /**
    * Site Phone number
    */
    'orgPhoneNumber'?: string;
    /**
    * Email address for the org.
    */
    'orgEmail'?: string;
    /**
    * Email address for the site.
    */
    'siteEmail'?: string;
    /**
    * Site user(s)
    */
    'siteUsers'?: Array<SiteUserRequest>;
    /**
    * Site amenitys(s)
    */
    'siteAmenities'?: Array<SiteAmenityRequest>;
    /**
    * Refresh token of the user.
    */
    'refreshToken': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "orgName",
            "baseName": "orgName",
            "type": "string"
        },
        {
            "name": "siteName",
            "baseName": "siteName",
            "type": "string"
        },
        {
            "name": "skip",
            "baseName": "skip",
            "type": "Array<string>"
        },
        {
            "name": "orgAddress",
            "baseName": "orgAddress",
            "type": "GenericAddressRequestDto"
        },
        {
            "name": "siteAddress",
            "baseName": "siteAddress",
            "type": "GenericAddressRequestDto"
        },
        {
            "name": "sitePhoneNumber",
            "baseName": "sitePhoneNumber",
            "type": "string"
        },
        {
            "name": "orgPhoneNumber",
            "baseName": "orgPhoneNumber",
            "type": "string"
        },
        {
            "name": "orgEmail",
            "baseName": "orgEmail",
            "type": "string"
        },
        {
            "name": "siteEmail",
            "baseName": "siteEmail",
            "type": "string"
        },
        {
            "name": "siteUsers",
            "baseName": "siteUsers",
            "type": "Array<SiteUserRequest>"
        },
        {
            "name": "siteAmenities",
            "baseName": "siteAmenities",
            "type": "Array<SiteAmenityRequest>"
        },
        {
            "name": "refreshToken",
            "baseName": "refreshToken",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CreateDefaultDataRequest.attributeTypeMap;
    }
}

