/**
 * ManageSpace Onboarding API
 * ManageSpace Onboarding API Documentation
 *
 * The version of the OpenAPI document: 0.0.12-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ImportResponse {
    /**
    * Unique identifier for the import.
    */
    'importId': string;
    /**
    * Organization identifier.
    */
    'orgId': string;
    /**
    * Site identifier.
    */
    'siteId': string;
    /**
    * Code name of one of the entity type.
    */
    'entityTypeCodeName': ImportResponse.EntityTypeCodeNameEnum;
    /**
    * File name of the import.
    */
    'fileName': string;
    /**
    * Start time of the import.
    */
    'startedAt': Date;
    /**
    * Finish time of the import.
    */
    'finishedAt'?: Date;
    /**
    * Indicates if the import was successful.
    */
    'successful': boolean;
    /**
    * Error message if any.
    */
    'errorMessage'?: string;
    /**
    * Error line if any.
    */
    'errorLine'?: number;
    /**
    * Creation time of the import.
    */
    'createdAt'?: Date;
    /**
    * Identifier of the creator of the import.
    */
    'createdBy'?: string;
    /**
    * Full name of the creator of the import.
    */
    'createdByFullName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "importId",
            "baseName": "importId",
            "type": "string"
        },
        {
            "name": "orgId",
            "baseName": "orgId",
            "type": "string"
        },
        {
            "name": "siteId",
            "baseName": "siteId",
            "type": "string"
        },
        {
            "name": "entityTypeCodeName",
            "baseName": "entityTypeCodeName",
            "type": "ImportResponse.EntityTypeCodeNameEnum"
        },
        {
            "name": "fileName",
            "baseName": "fileName",
            "type": "string"
        },
        {
            "name": "startedAt",
            "baseName": "startedAt",
            "type": "Date"
        },
        {
            "name": "finishedAt",
            "baseName": "finishedAt",
            "type": "Date"
        },
        {
            "name": "successful",
            "baseName": "successful",
            "type": "boolean"
        },
        {
            "name": "errorMessage",
            "baseName": "errorMessage",
            "type": "string"
        },
        {
            "name": "errorLine",
            "baseName": "errorLine",
            "type": "number"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date"
        },
        {
            "name": "createdBy",
            "baseName": "createdBy",
            "type": "string"
        },
        {
            "name": "createdByFullName",
            "baseName": "createdByFullName",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ImportResponse.attributeTypeMap;
    }
}

export namespace ImportResponse {
    export enum EntityTypeCodeNameEnum {
        Contacts = <any> 'contacts',
        MapFeatures = <any> 'map_features',
        Rentals = <any> 'rentals',
        Units = <any> 'units'
    }
}
