/**
 * ManageSpace Onboarding API
 * ManageSpace Onboarding API Documentation
 *
 * The version of the OpenAPI document: 0.0.11-dev
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ResetDataResponse {
    /**
    * Organization ID
    */
    'orgId': string;
    /**
    * Workflow Definition ids, that have been deleted.
    */
    'workflowDefinitionIds': Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "orgId",
            "baseName": "orgId",
            "type": "string"
        },
        {
            "name": "workflowDefinitionIds",
            "baseName": "workflowDefinitionIds",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return ResetDataResponse.attributeTypeMap;
    }
}

